### ISSUE TITLE
Info about chests.yml

### ISSUE THREAD

**Issue by jfernandz** [MC-Minigames/MGSkyWars#14]
I would like to know what does mean in default config the line

`items: 5*64;5*64;5*64;5*64;262*64;278*1;5*64%30` 

Concretely, why so many `5*64` and why the `%30`? 

Also I've done my own config 

```
# Just copy paste if you want more chests. The percentages must add up to 100!
config:
  enabled: true
  chests:
    chest1:
      items: 5*64;262*64;278*1;287*3
      percentage: 10
    chest2:
      items: 5*64;262*64;276*1;287*3
      percentage: 20
    chest3:
      items: 5*64;262*64
      percentage: 35
    chest4:
      items: 5*64;262*64
      percentage: 35
```

But still appears a few incomplete chests, like this:

![captura de pantalla de 2017-03-24 22-18-46](https://cloud.githubusercontent.com/assets/4059108/24315143/b7bfbdb4-10e5-11e7-8c53-b84102db6b56.png)

I've not setup any chest with only `wood, string and arrows`

What do you think? Thank you!
